version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: DockerFile-backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4001:4000"
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always
  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres