version: "3.5"

services:
  server:
    image: asd0300/g-server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4001:4000"
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always
    environment:
      - Password=
      - Name=postgres
      - DBname=postgres
      - Addr=172.19.0.4
      - Username=postgres
    networks:
          Poya:
            ipv4_address: 172.19.0.3
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      # 設定超級用戶密碼
      - POSTGRES_PASSWORD=
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
          Poya:
            ipv4_address: 172.19.0.4
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      Poya:
        ipv4_address: 172.19.0.5
networks:
  Poya:
    external: true