definitions:
  pojo.Product:
    properties:
      createdate:
        type: string
      id:
        type: integer
      newprice:
        type: integer
      otherpic:
        type: string
      price:
        type: integer
      title:
        type: string
      titlepic:
        type: string
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Swagger PoYa Site API
  version: "1.0"
paths:
  /v1/products/:
    get:
      consumes:
      - application/json
      description: Get all product items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ProductSeries
      tags:
      - FindAllProducts
swagger: "2.0"
