-- DROP TABLE IF EXISTS players;
-- DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS users;
CREATE TABLE players (
 id SERIAL PRIMARY KEY,
 age SMALLINT NOT NULL,
 username VARCHAR(50) NOT NULL,
 budget INTEGER
);
CREATE TABLE games (
 id SERIAL PRIMARY KEY,
 winner_id SMALLINT NOT NULL,
 location VARCHAR(50) NOT NULL,
 prize INTEGER
);
CREATE TABLE users (
 id SERIAL PRIMARY KEY,
 name VARCHAR(50) NOT NULL,
 password VARCHAR(50) NOT NULL
);